kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080 # maps to frontend Service nodePort
        hostPort: 80
        listenAddress: "0.0.0.0"
        protocol: TCP
      - containerPort: 30081 # maps to backend Service nodePort
        hostPort: 5000
        listenAddress: "0.0.0.0"
        protocol: TCP
