apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
      - name: flask-backend
        image: flask-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-backend
  namespace: app
spec:
  type: NodePort
  selector:
    app: flask-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-frontend
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-frontend
  template:
    metadata:
      labels:
        app: express-frontend
    spec:
      containers:
      - name: express-frontend
        image: express-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: express-frontend
  namespace: app
spec:
  type: NodePort
  selector:
    app: express-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30080
